OnlineShopProject/Models/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}

OnlineShopProject/Controllers/CategoryController.cs
using OnlineShopProject.Models;
using OnlineShopProject.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShopProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        CategoryRepository catRepo = new CategoryRepository();
        // GET: Category
        public ActionResult Index()
        {
            return View(catRepo.GetAll());
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category cat)
        {
            
            ViewBag.success = "Category Added Successfyll!";
            catRepo.Insert(cat);
            return RedirectToAction("Index");
            
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(catRepo.Get(id));
        }
        [HttpPost]
        public ActionResult Edit(Category cat)
        {
            catRepo.Update(cat);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(catRepo.Get(id));
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
            catRepo.Delete(id);
            return RedirectToAction("Delete");
        }
    }
}

OnlineShopProject/Views/Category/AddCategory.cshtml
@model OnlineShopProject.Models.Category

@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid">
    <!-- Breadcrumbs-->

    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item ">Categories</li>
        <li class="breadcrumb-item active">Add New Category</li>


    </ol>
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i>
            Add New Category

        </div>
        <div class="card-body">
            @using (Html.BeginForm("AddCategory", "Category", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.HiddenFor(model => model.CategoryId)

                <div class="form-group">
                    <label class="control-label">Category Name</label>

                    @Html.TextBoxFor(m => m.CategoryName, new { @class = "form-control", placeholder = "Enter category Name", required = "required", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(m => m.CategoryName, "", new { @class = "text-danger" })
                </div>

                <a onclick="window.history.back();" class="btn btn-danger">Cancel</a>
                <input type="submit" class="btn btn-success" value="Save" />
            }


        </div>
    </div>
</div>



@*

    @model OnlineShopProject.Models.Category

    @{
        ViewBag.Title = "AddCategory";
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }

    <div class="container-fluid">
        <!-- Breadcrumbs-->

        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="#">Dashboard</a>
            </li>
            <li class="breadcrumb-item ">Categories</li>
            <li class="breadcrumb-item active">Add New Category</li>


        </ol>
        <!-- DataTables Example -->
        <div class="card mb-3">
            <div class="card-header">
                <i class="fas fa-table"></i>
                Add New Category

            </div>
            <div class="card-body">
                @using (Html.BeginForm("AddCategory", "Category", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.HiddenFor(model => model.CategoryId)

                    <div class="form-group">
                        <label class="control-label">Category Name</label>

                        @Html.TextBoxFor(m => m.CategoryName, new { @class = "form-control", placeholder = "Enter category Name", required = "required", autofocus = "autofocus" })
                        @Html.ValidationMessageFor(m => m.CategoryName, "", new { @class = "text-danger" })
                    </div>

                    <a onclick="window.history.back();" class="btn btn-danger">Cancel</a>
                    <input type="submit" class="btn btn-success" value="Save" />
                }


            </div>
        </div>
    </div>



*@

OnlineShopProject/Views/Category/Delete.cshtml
@model OnlineShopProject.Models.Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div>
    @Html.HiddenFor(model => model.CategoryId)

    <div class="form-group">
        <div class="col-md-4">
            <label class="control-label">Category Name</label>

            @Html.DisplayNameFor(model => model.CategoryName)
            @Html.DisplayFor(model => model.CategoryName)
        </div>
    </div>

  @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" data-toggle="modal" data-target="#exampleModal" class="btn btn-Info" />
        </div>
    }

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <strong class="text-danger">Are you sure you want to delete this?</strong>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    @using (Html.BeginForm("Delete", "Category", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                    
                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-success" />
                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

OnlineShopProject/Views/Category/Edit.cshtml
@model OnlineShopProject.Models.Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid">
    <!-- Breadcrumbs-->

    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item ">Categories</li>
        <li class="breadcrumb-item active">Update Category</li>


    </ol>
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i>
            Update Category
        </div>
        <div class="card-body">
            @using (Html.BeginForm("Edit", "Category", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.HiddenFor(model => model.CategoryId)

                <div class="form-group">
                    <label class="control-label">Category Name</label>

                    @Html.TextBoxFor(m => m.CategoryName, new { @class = "form-control", placeholder = "Enter category Name", required = "required", autofocus = "autofocus" })
                    @Html.ValidationMessageFor(m => m.CategoryName, "", new { @class = "text-danger" })
                </div>

                <a onclick="window.history.back();" class="btn btn-danger">Cancel</a>
                <input type="submit" class="btn btn-success" value="Save" />
            }
        </div>
    </div>
</div>

OnlineShopProject/Views/Category/Index.cshtml
@model IEnumerable<OnlineShopProject.Models.Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{int count = 0; }


<div class="container-fluid">
     @*Breadcrumbs*@
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Categories</li>
    </ol>
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table text-primary"></i>
            Category Details
            <a href="@Url.Action("AddCategory", "Category")" class="btn btn-info float-right fa fa-plus">Add Catagory</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover text-center" id="dataTable" width="100%" cellspacing="0">
                    <thead class="thead-light">
                        <tr>
                            <th>Sr. No.</th>
                            <th>Category Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            count = count + 1;
                            <tr>
                                <td>@count</td>
                                <td>@item.CategoryName</td>
                                <td>
                                    <span title="Update">@Html.ActionLink(" ", "Edit", "Category", new { id = item.CategoryId }, new { @class = "btn text-info fa fa-pencil-alt" })</span>
                                    <span title="Remove">@Html.ActionLink(" ", "Delete", "Category", new { id = item.CategoryId }, new { @class = "btn text-danger fa fa-trash-alt" })</span>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>