OnlineShopProject/Controllers/SliderController.cs
using OnlineShopProject.Models;
using OnlineShopProject.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace OnlineShopProject.Controllers
{
    public class SliderController : Controller
    {
        SliderRepository SR = new SliderRepository();
        Slider2Repository SR2 = new Slider2Repository();
        // GET: Slider
        public ActionResult Index()
        {
            return View(SR.GetAll());
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(SR.Get(id));
        }
        [HttpPost]
        public ActionResult Edit(SlideImage sd, HttpPostedFileBase file)
        {
            string pic = null;
            if (file != null)
            {
                pic = System.IO.Path.GetFileName(file.FileName);
                string path = System.IO.Path.Combine(Server.MapPath("~/I_SliderImg/"), pic);
                // file is uploaded
                file.SaveAs(path);
            }
            sd.SlideImage1 = pic;
            SR.Update(sd);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Slider2()
        {
            return View(SR2.GetAll());
        }

        [HttpGet]
        public ActionResult Slide2Edit(int id)
        {
            return View(SR2.Get(id));
        }
        [HttpPost]
        public ActionResult Slide2Edit(SlideImage2 si2, HttpPostedFileBase file)
        {
            string pic = null;
            if (file != null)
            {
                pic = System.IO.Path.GetFileName(file.FileName);
                string path = System.IO.Path.Combine(Server.MapPath("~/I_SliderImg/"), pic);
                // file is uploaded
                file.SaveAs(path);
            }
            si2.SlideImage = pic;
            SR2.Update(si2);
            return RedirectToAction("Index");
        }
    }
}

OnlineShopProject/Views/Slider/Edit.cshtml
@model OnlineShopProject.Models.SlideImage

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>SlideImage</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.SlideId)

    <div class="form-group">
        @Html.LabelFor(model => model.SlideTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SlideTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SlideTitle, "", new { @class = "text-danger", required = "required", autofocus = "autofocus" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.SlideCollection,"Collection Message", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SlideCollection, new { htmlAttributes = new { @class = "form-control", required = "required", autofocus = "autofocus" } })
            @Html.ValidationMessageFor(model => model.SlideCollection, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.SlideImage1, "Choose Image", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    <input type="file" name="file" id="file" required style="width: 100%;" />
                    @Html.ValidationMessageFor(model => model.SlideImage1, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Update" class="btn btn-success" />
        </div>
    </div>
</div>
}

OnlineShopProject/Views/Slider/Index.cshtml
@model IEnumerable<OnlineShopProject.Models.SlideImage>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@{int counts = 1; }
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Slider
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover text-center" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Sr. No.</th>
                        <th>Title</th>
                        <th>Message</th>
                        <th>Image</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@counts</td>
                            <td>@item.SlideTitle</td>
                            <td>@item.SlideCollection</td>
                            <td>@item.SlideImage1</td>
                            <td>
                                @Html.ActionLink(" ", "Edit", "Slider", new { id = item.SlideId }, new { @class = "btn text-info fa fa-pencil-alt" })
                            </td>
                        </tr>
                        counts++;
                    }

                </tbody>
            </table>
        </div>

    </div>
</div>

OnlineShopProject/Views/Slider/Slide2Edit.cshtml
@model OnlineShopProject.Models.SlideImage2

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SlideImage</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SlideId)

        <div class="form-group">
            @Html.LabelFor(model => model.SideTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SideTitle, new { htmlAttributes = new { @class = "form-control", required = "required", autofocus = "autofocus" } })
                @Html.ValidationMessageFor(model => model.SideTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SlideCollection, "Collection Message", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SlideCollection, new { htmlAttributes = new { @class = "form-control", required = "required", autofocus = "autofocus" } })
                @Html.ValidationMessageFor(model => model.SlideCollection, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">

                <div class="form-group">
                    @Html.LabelFor(model => model.SlideImage, "Choose Image", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">

                        <input type="file" name="file" id="file" required style="width: 100%;" />
                        @Html.ValidationMessageFor(model => model.SlideImage, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-success" />
            </div>
        </div>
    </div>
}

OnlineShopProject/Views/Slider/Slider2.cshtml
@model IEnumerable<OnlineShopProject.Models.SlideImage2>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@{int counts = 1; }
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Slider
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover text-center" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Sr. No.</th>
                        <th>Title</th>
                        <th>Message</th>
                        <th>Image</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@counts</td>
                        <td>@item.SideTitle</td>
                        <td>@item.SlideCollection</td>
                        <td>@item.SlideImage</td>
                        <td>
                            @Html.ActionLink(" ", "Slide2Edit", "Slider", new { id = item.SlideId }, new { @class = "btn text-info fa fa-pencil-alt" })
                        </td>
                    </tr>
                        counts++;
                    }

                </tbody>
            </table>
        </div>

    </div>
</div>